import type { Member } from "@/lib/types";
import { pic } from "./Portraits.image";

export const MEMBERS: Member[] = [
  {
    id: "m1",
    name: "Abhishek Saboo",
    convention: "Jacquards Weaver",
    company: "Saboo Textiles",
    specialty: "Textiles",
    oneliner:
      "Premium jacquard weaving for fashion houses across India. Three-generation family loom now exporting to Milan and...",
    photo: pic("m", 0),
    location: "Pandesara, Surat",
    joined: "Since 2002",
  },
  {
    id: "m2",
    name: "Hetal Mehta",
    convention: "Numbers Whisperer",
    company: "Mehta & Associates",
    specialty: "Chartered Accountancy",
    oneliner:
      "Tax & advisory for family businesses navigating succession, GST, and cross-border textile exports.",
    photo: pic("f", 0),
    location: "Athwa, Surat",
    joined: "Since 2009",
  },
  {
    id: "m3",
    name: "Rohan Choksi",
    convention: "Stone Reader",
    company: "Choksi Diamonds",
    specialty: "Diamond Trading",
    oneliner:
      "Solitaires sourced from Antwerp & Mumbai. Specialises in 1ct+ certified diamonds for bridal jewellers.",
    photo: pic("m", 1),
    location: "Varachha, Surat",
    joined: "Since 2014",
  },
  {
    id: "m4",
    name: "Priya Nanavati",
    convention: "Frame Maker",
    company: "Studio Nanavati",
    specialty: "Photography",
    oneliner:
      "Wedding & brand photography. Documentary style, six-figure portfolio of Gujarat's family-run brands.",
    photo: pic("f", 1),
    location: "Vesu, Surat",
    joined: "Since 2016",
  },
  {
    id: "m5",
    name: "Karan Desai",
    convention: "Code Carpenter",
    company: "Desai Tech Labs",
    specialty: "IT & Software",
    oneliner: "Custom ERP for textile manufacturers.",
    photo: pic("m", 2),
    location: "Piplod, Surat",
    joined: "Since 2018",
  },
  {
    id: "m6",
    name: "Anjali Shah",
    convention: "Light Architect",
    company: "Shah Designs",
    specialty: "Architecture",
    oneliner: "Residential architecture across Gujarat.",
    photo: pic("f", 2),
    location: "Adajan, Surat",
    joined: "Since 2021",
  },
  {
    id: "m7",
    name: "Vivek Patel",
    convention: "Money Mover",
    company: "Patel Wealth",
    specialty: "Wealth Management",
    oneliner: "Portfolio advisory for HNIs.",
    photo: pic("m", 3),
    location: "Pandesara, Surat",
    joined: "Since 2002",
  },
  {
    id: "m8",
    name: "Nirali Kothari",
    convention: "Gold Seeker",
    company: "Kothari Jewellers",
    specialty: "Jewellery",
    oneliner: "Bridal sets, four generations in.",
    photo: pic("f", 3),
    location: "Athwa, Surat",
    joined: "Since 2009",
  },
  {
    id: "m9",
    name: "Manish Trivedi",
    convention: "Loom Master",
    company: "Trivedi Textiles",
    specialty: "Textiles",
    oneliner: "Specialized in silk and cotton blends for global retail.",
    photo: pic("m", 4),
    location: "Vesu, Surat",
    joined: "Since 2012",
  },
  {
    id: "m10",
    name: "Rina Bhatia",
    convention: "Gem Expert",
    company: "Bhatia Diamonds",
    specialty: "Diamond Trading",
    oneliner: "High-clarity rough diamond sourcing and trading.",
    photo: pic("f", 4),
    location: "Adajan, Surat",
    joined: "Since 2015",
  },
  {
    id: "m11",
    name: "Devang Gandhi",
    convention: "Visual Storyteller",
    company: "Gandhi Studios",
    specialty: "Photography",
    oneliner: "Capturing the soul of industrial Surat.",
    photo: pic("m", 5),
    location: "Piplod, Surat",
    joined: "Since 2017",
  },
  {
    id: "m12",
    name: "Sneha Joshi",
    convention: "Diamond Stylist",
    company: "Joshi Jewels",
    specialty: "Jewellery",
    oneliner: "Curating bespoke collections for modern brides.",
    photo: pic("f", 5),
    location: "Athwa, Surat",
    joined: "Since 2020",
  },
];
